/**
 * ZIP EXPORT UTILITIES - Export projects as downloadable ZIP archives
 * 
 * Purpose: Create and download ZIP files containing project files and structure
 * Used by: Project export feature, download functionality
 * Key Features: ZIP creation, file structure preservation, metadata inclusion, browser download
 */

import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import type { ProjectFile, Project } from '@/lib/types';

// Export project as ZIP file
export async function exportProjectAsZip(
  project: Project,
  files: ProjectFile[],
  onProgress?: (percent: number) => void
): Promise<void> {
  try {
    console.log(`[ZIP Export] Starting export for ${files.length} files...`);
    const zip = new JSZip();
    
    let filesAdded = 0;
    let filesSkipped = 0;
    
    // Add project files to ZIP
    for (const file of files) {
      if (file.type === 'file') {
        if (file.content && file.content.trim().length > 0) {
          // Remove leading slash from path for ZIP
          const zipPath = file.path.startsWith('/') ? file.path.slice(1) : file.path;
          zip.file(zipPath, file.content);
          filesAdded++;
        } else {
          console.warn(`[ZIP Export] Skipping file with no content: ${file.path}`);
          filesSkipped++;
        }
      }
    }
    
    console.log(`[ZIP Export] Added ${filesAdded} files, skipped ${filesSkipped} files`);
    
    // Add README with project info
    const readme = generateProjectReadme(project);
    zip.file('README.md', readme);
    
    console.log(`[ZIP Export] Compressing files...`);
    
    // Generate ZIP blob with progress tracking
    const blob = await zip.generateAsync({ 
      type: 'blob',
      compression: 'DEFLATE',
      compressionOptions: {
        level: 6
      }
    }, (metadata) => {
      const progress = Math.floor(metadata.percent);
      console.log(`[ZIP Export] Compression progress: ${progress}%`);
      if (onProgress) {
        onProgress(progress);
      }
    });
    
    console.log(`[ZIP Export] ZIP created, size: ${(blob.size / 1024).toFixed(2)} KB`);
    
    // Download the ZIP file
    const fileName = `${project.title || project.slug || 'project'}.zip`;
    console.log(`[ZIP Export] Triggering download: ${fileName}`);
    saveAs(blob, fileName);
    
    // Wait a bit for saveAs to trigger
    await new Promise(resolve => setTimeout(resolve, 100));
    
    console.log(`[ZIP Export] Export complete!`);
    
  } catch (error) {
    console.error('[ZIP Export] Error exporting project as ZIP:', error);
    throw new Error('Failed to export project as ZIP');
  }
}

// Generate README content for the project
function generateProjectReadme(project: Project): string {
  const framework = project.framework || 'react';
  
  return `# ${project.title}

${project.description ? `${project.description}\n\n` : ''}

## Project Information

- **Framework**: ${framework.charAt(0).toUpperCase() + framework.slice(1)}
- **Created**: ${new Date(project.$createdAt).toLocaleDateString()}
- **Last Updated**: ${new Date(project.$updatedAt).toLocaleDateString()}

## Getting Started

### Prerequisites

Make sure you have Node.js installed on your machine.

### Installation

1. Extract this ZIP file to your desired location
2. Open a terminal in the project directory
3. Install dependencies:

\`\`\`bash
npm install
# or
yarn install
# or
pnpm install
\`\`\`

### Development

Start the development server:

\`\`\`bash
npm run dev
# or
yarn dev
# or
pnpm dev
\`\`\`

${getFrameworkSpecificInstructions(framework)}

## Project Structure

This project was generated using VibeIt and follows modern web development best practices.

## Support

If you encounter any issues, please check the documentation for your chosen framework:

${getFrameworkDocumentationLinks(framework)}

---

*Generated by VibeIt*
`;
}

// Get framework-specific instructions
function getFrameworkSpecificInstructions(framework: string): string {
  switch (framework) {
    case 'react':
      return `
### React Development

- The app will be available at \`http://localhost:3000\`
- Edit files in the \`src\` directory
- The page will reload automatically when you make changes
- Check the browser console for any errors

### Building for Production

\`\`\`bash
npm run build
\`\`\`

This creates an optimized production build in the \`build\` directory.
`;

    case 'vue':
      return `
### Vue Development

- The app will be available at \`http://localhost:8080\`
- Edit files in the \`src\` directory
- The page will reload automatically when you make changes
- Check the browser console for any errors

### Building for Production

\`\`\`bash
npm run build
\`\`\`

This creates an optimized production build in the \`dist\` directory.
`;

    case 'vanilla':
      return `
### Vanilla JavaScript Development

- Open \`index.html\` in your browser or use a local server
- For development with live reload, you can use:

\`\`\`bash
npx serve .
# or
python -m http.server 8000
\`\`\`

- Edit HTML, CSS, and JavaScript files directly
- Refresh the browser to see changes
`;

    default:
      return `
### Development

- Follow the framework-specific instructions for ${framework}
- Check the package.json file for available scripts
`;
  }
}

// Get framework documentation links
function getFrameworkDocumentationLinks(framework: string): string {
  switch (framework) {
    case 'react':
      return `
- [React Documentation](https://reactjs.org/docs)
- [Create React App Documentation](https://create-react-app.dev/docs)
- [React Router](https://reactrouter.com/)
`;

    case 'vue':
      return `
- [Vue.js Documentation](https://vuejs.org/guide/)
- [Vue CLI Documentation](https://cli.vuejs.org/)
- [Vue Router](https://router.vuejs.org/)
`;

    case 'vanilla':
      return `
- [MDN Web Docs](https://developer.mozilla.org/)
- [JavaScript Guide](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide)
- [HTML Reference](https://developer.mozilla.org/en-US/docs/Web/HTML)
- [CSS Reference](https://developer.mozilla.org/en-US/docs/Web/CSS)
`;

    default:
      return `
- Check the official documentation for ${framework}
`;
  }
}
